# Generated by Django 5.1.3 on 2024-11-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0003_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='not_started', max_length=20),
        ),
    ]
